sudo: true

language: cpp

git:
  depth: 3

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-5
    - os: osx
      osx_image: xcode7.1
      compiler: clang

install:
  - ./.travis/install_dependencies.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  