language: cpp

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y build-essential g++-5 software-properties-common libboost-all-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-5"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:george-edison55/cmake-3.x; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir 3rdParty && cd 3rdParty; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/opencv/opencv.git ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir opencv/build && cd opencv/build; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j4; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf';fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../../..; fi 

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --with-clang llvm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install opencv; fi

script:
  - cd FastAnnotationTool
  - mkdir build
  - cd build
  - cmake ..
  - make
  