language: cpp

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/linux_dependencies.sh; fi 

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis/osx_dependencies.sh; fi

script:
  - cd FastAnnotationTool
  - mkdir build
  - cd build
  - cmake ..
  - make
  