# Site settings
title: Oussama Ennafii
header-img: img/home-bg.jpg
email: oussama.ennafii@outlook.com
copyright_name: Oussama Ennafii
description: "Personal Website."
baseurl: "https://ethiy.github.io"
url: "FastImageAnnotationTool/"
github_username:  Ethiy
linkedin_username: oussama-ennafii
email_username:  oussama.ennafii@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
